### ISSUE TITLE
Two small bugs in the code

### ISSUE THREAD

**Issue by toothacher17** [dmlc/experimental-lda#4]
I have found two very small bugs, not influencing the performance or the accuracy. They are in the singleLDA\model.cpp file:

(1). sorting list of pairs based on the second value of a pair in model::save_model_twords().

![image](https://cloud.githubusercontent.com/assets/7029845/11315980/a83107d4-8fc9-11e5-8ff7-7a06db8dc774.png)

should be changed to:
![image](https://cloud.githubusercontent.com/assets/7029845/11315982/b9f7680a-8fc9-11e5-98b4-7adaddec6d99.png)

I tested on my own code, and it is working now to save the top n words for each topic

(2). A typo in the model:~model():

![image](https://cloud.githubusercontent.com/assets/7029845/11315989/df1cadde-8fc9-11e5-92a2-7b001e731f73.png)

The code is super cool and fast, and well designed and documented in details so easy to use. Thanks for sharing

**Comment by xiangcong** [comment]
Thanks for sharing what you found!
I run the parallelLDA but find that the likelihood is always -1.#IND.
Do you know why?

**Comment by manzilzaheer** [comment]
Thanks for pointing it out. Fixed now!
